= Data Flow

[mermaid,data_flow,png]
----
flowchart LR
    d1-->b1 & b2 & b3
    d2-->b4 & b5 & b6

	subgraph Data Sources
    d1@{ shape: doc, label: "CRM" }
	d2@{ shape: doc, label: "ERP" }
    end

    subgraph Bronze Layer
    b1@{ shape: div-rect, label: "crm_cust_info" }
	b2@{ shape: div-rect, label: "crm_prd_inf" }
	b3@{ shape: div-rect, label: "crm_sales_details" }
    
	b4@{ shape: div-rect, label: "erp_cust_az12" }
	b5@{ shape: div-rect, label: "erp_loc_a101" }
	b6@{ shape: div-rect, label: "erp_px_cat_g1v2" }
    end
----

== Specifications

The chosen data flow results from the following specifications:

[cols="2,3,3,3", options="header"]
|===
|*Category* |*Bronze Layer* |*Silver Layer* |*Gold Layer*

|*Definition*
| Raw, unprocessed data as-is from sources
| Clean & standardized data
| Business-Ready data

|*Objective*
| Traceability & Debugging
| (Intermediate Layer) Prepare Data for Analysis
| Provide data to be consumed for reporting & Analytics

|*Object Type*
| Tables
| Tables
| Views

|*Load Method*
| Full Load (Truncate & Insert)
| Full Load (Truncate & Insert)
| None

|*Data Transformation*
| None (as-is)
| Data Cleaning +
Data Standardization +
Data Normalization +
Derived Columns +
Data Enrichment
| Data Integration +
Data Aggregation +
Business Logic & Rules

|*Data Modeling*
| None (as-is)
| None (as-is)
| Star Schema +
Aggregated Objects +
Flat Tables

|*Target Audience*
| Data Engineers
| Data Analysts +
Data Engineers
| Data Analysts +
Business Users
|===

